project_name: retup
dist: target/dist
before:
  hooks:
    - make clean
    - make vendor
builds:
  - goos:
      - linux
      - windows
      - darwin
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=netgo
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
